CREATE TABLE usuarios (
id INTEGER PRIMARY KEY,
nome TEXT NOT NULL,
email TEXT UNIQUE NOT NULL
);
CREATE TABLE pedidos (
id INTEGER PRIMARY KEY,
usuario_id INTEGER NOT NULL,
FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
CREATE TABLE itens_pedido (
id INTEGER PRIMARY KEY AUTOINCREMENT,
pedido_id INTEGER NOT NULL,
nome TEXT NOT NULL,
quantidade INTEGER NOT NULL,
FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE CASCADE
);
 